---
machine:
  image: "ubuntu/bionic64"
  memory: "2048"
  cpus: "3"

nodes:
  - ip: 10.0.0.2
    role: master
  - ip: 10.0.0.3
    role: worker
  - ip: 10.0.0.4
    role: worker
#  - ip: 10.0.0.5
#    role: worker
